language: node_js
node_js:
  - 0.10

services:
  - mysql
  - postgresql

env:
  global:
    - NODE_ENV=test

notifications:
  email:
    recipients:
      - kevin@vidigami.com

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mysql -e 'create database test_backbone_sql;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - psql -c 'create database test_backbone_sql;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'root';" -U postgres
